### ISSUE TITLE
3.4.0 introduced breaking changes (dropping Node 6 support)

### ISSUE THREAD

**Issue by rwjblue** [socketio/engine.io#589] opened 2019-09-23 14:04 UTC
I am very sorry to raise such an issue (I know its often pretty frustrating as a maintainer to have someone else tell me about "semver violations"), please understand that I am only reporting because _I_ would also want to be aware of issues that consumers of my packages are facing.

The `ws` updated landed in https://github.com/socketio/engine.io/pull/587 was a breaking change and releasing that updated as 3.4.0 means existing consumers that still support Node 6 environments are now broken. Since `ws@7` drops support for Node 6 (for example, it uses object rest/spread), any Node 6 consumers that had been using `^3.3.1` (which worked fine) will now get `3.4.0` and receive errors when `ws`'s `lib/websocket.js` is required.

Thank you for your time (and again, I apologize for the distasteful issue).

**Comment by nitbaby** [comment] 2019-09-25 08:31
Thanks for raising this issue. We are also stuck due to this

**Comment by nsgundy** [comment] 2019-11-13 12:11
Also ran into this issue. Clearly stating this minimum version requirement with the `engines` property in `package.json` would be appreciated so that one would know about it at the time of installing the package rather than finding out when running the code.

**Comment by darrachequesne** [comment] 2020-04-15 12:25
Arf, sorry for that... I added the `engines` property in the package.json file in both [master](https://github.com/socketio/engine.io/commit/61e639b257c91f88200276122816b0514fb396df) and [3.4.x](https://github.com/socketio/engine.io/commit/21ef608a1f608f805f68df8cc7cbcc9685c5e380) branches, in order not to reproduce the error.

**Comment by darrachequesne** [comment] 2020-04-15 12:26
Closing now, as I don't think we can do anything else.

**Closed by darrachequesne** 2020-04-15 12:26 UTC
