### ISSUE TITLE
Make sendErrorMessage response available on server

### ISSUE THREAD

**Issue by mrazf** [socketio/engine.io#576] opened 2019-04-16 21:15 UTC
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/engine.io) or [slack](https://socketio.slack.com)

### You want to:

* [] report a *bug*
* [x] request a *feature*

### Current behaviour

Apologies if this is my misunderstanding of NodeJS streams.

The HTTP body of [`sendErrorMessage`](https://github.com/socketio/engine.io/blob/master/lib/server.js#L245) is readable on the client but does not appear to be accessible server side.

I'm currently investigating a number of 400 errors produced [here](https://github.com/socketio/engine.io/blob/master/lib/server.js#L265) but it looks like this could be 1 of 4 `Server.errorMessages`.

Are the response bodies available server side or would it be possible to add some debug logging that includes the body before sending the response?

### Setup
- OS:
- browser:
- engine.io version:

**Comment by Khez** [comment] 2021-03-16 10:17
We've noticed a very similar issue in production as well and came to the same conclusions.

We **believe** the root cause is a faulty proxy between a client and our socket.io implementation. But unfortunately we can't confirm it.

## Flow
Delving through the logs, we found the same code in engine.io v3.x being the culprit:
- [During server.attach](https://github.com/socketio/engine.io/blob/3.5.0/lib/server.js#L440)
- [A handler for server.on('request') is added](https://github.com/socketio/engine.io/blob/3.5.0/lib/server.js#L464)
- [Which handles the request directly](https://github.com/socketio/engine.io/blob/3.5.0/lib/server.js#L214)
- [Calls sendErrorMessage if it fails](https://github.com/socketio/engine.io/blob/3.5.0/lib/server.js#L243)

## Problem
This entire scenario is completely hidden from the underlying server.

Checking the code it seems there are a number of different errors that can cause this:
- [An unknown transport](https://github.com/socketio/engine.io/blob/3.5.0/lib/server.js#L140)
- [An invalid origin](https://github.com/socketio/engine.io/blob/3.5.0/lib/server.js#L148)
- [An invalid SID](https://github.com/socketio/engine.io/blob/3.5.0/lib/server.js#L156)
- [An unexpected transport without upgrade](https://github.com/socketio/engine.io/blob/3.5.0/lib/server.js#L160)
- [An invalid HTTP Method](https://github.com/socketio/engine.io/blob/3.5.0/lib/server.js#L164)
- [Transport handshake error](https://github.com/socketio/engine.io/blob/3.5.0/lib/server.js#L311)
- If using socket.io, there's also:
    - [a default origin check](https://github.com/socketio/socket.io/blob/2.4.1/lib/index.js#L69)
    - [a userland origin check](https://github.com/socketio/socket.io/blob/2.4.1/lib/index.js#L75)

So together there are **8 separate problems** that lead to either **400** or **403** status code, the only difference being the **json output**, which itself has [5 distinct results](https://github.com/socketio/engine.io/blob/3.5.0/lib/server.js#L80)

## Solution
Since we're already using [emit for connection](https://github.com/socketio/engine.io/blob/3.5.0/lib/server.js#L342), we could add an emit for these scenarios as well.

If there's no problem with a similar solution I can help with a PR (maybe on both 3.x and 4.x branches)

**Comment by darrachequesne** [comment] 2021-03-16 22:03
@Khez Thanks for the detailed explanation. Do you have a suggestion for the API?

Related: https://github.com/socketio/socket.io/issues/3819

**Comment by Khez** [comment] 2021-03-19 23:38
It feels like emitting an event was proposed https://github.com/socketio/socket.io/issues/3819 as well :) 

To be honest, it kind of depends on what people need. Is it a hook that can change things or just a means to logging ?

@darrachequesne  I'm going to try to make a PR over the weekend on the 3.4.x branch then we could port it to 3.5.x and master.  It will give me more insight into how to properly tackle this issue. Unless you believe in a different approach.

## Hooking into the error page
There might be a need to hook into and possibly even change the error page.

It doesn't seem that `engine.io-client` looks at what the underlying content of the error page is.
Meaning changes to the page should be backwards compatible with the client implementation.

I'd vote for this to be a separate issue / PR, since probably many users don't even know this scenario occurs.

### Note on error pages

It seems there are two separate ways of causing an error page and they are different:
- [abortConnection](https://github.com/socketio/engine.io/blob/4.1.1/lib/server.js#L511) with a default text/html error reason
- [sendErrorMessage](https://github.com/socketio/engine.io/blob/4.1.1/lib/server.js#L478) with a default application/json error

Feels like it should always be application/json. Uncertain why it is not.

## Hooking into the error codes
It seems @andrejleitner, @mrazf and myself just need a way to log this scenario.

With an update to make error codes unique, we could simply emit from [sendErrorMessage](https://github.com/socketio/engine.io/blob/3.5.0/lib/server.js#L243):
- [socket.io can then hook into this in it's bind handler](https://github.com/socketio/socket.io/blob/2.4.1/lib/index.js#L418)
- Emit the event from socket.io so we can do `io.on('connection_dropped', (reason) => console.log(reason))`
    - This similar to the already available `io.on('connection', (socket) => {})`

### Path of least resistance
We already have an [error list](https://github.com/socketio/engine.io/blob/3.5.0/lib/server.js#L72), some of which are unique with regard to the underlying issue.

We'd need to cover non-unique codes that are currently BAD_REQUEST:
- [INVALID_ORIGIN](https://github.com/socketio/engine.io/blob/3.5.0/lib/server.js#L148)
- [BAD_TRANSPORT / TRANSPORT_WITHOUT_UPGRADE](https://github.com/socketio/engine.io/blob/3.5.0/lib/server.js#L160)
- [TRANSPORT_HANDSHAKE_ERROR](https://github.com/socketio/engine.io/blob/3.5.0/lib/server.js#L311)
   - Probably the most beneficial PR would contain a way of accessing the underlying error 

With a change to the error codes, we could simply emit from [sendErrorMessage](https://github.com/socketio/engine.io/blob/3.5.0/lib/server.js#L243):
- Server.errorMessages[code] would represent all engine.io scenarios
- Server.errors.FORBIDDEN remains the result of allowRequest

This method would forces us to "skip" `Server.errorMessages[5]` which is used in branch 4.x by `UNSUPPORTED_PROTOCOL_VERSION`
Still wondering if a different parameter or a mild refactor of sendErrorMessage would be more beneficial.

**Comment by Khez** [comment] 2021-03-24 14:47
@darrachequesne any chance you can take a look through the PR so we can move this issue forward ?

I'm open to any and all suggestions :)

**Comment by darrachequesne** [comment] 2021-05-04 08:56
Closed by https://github.com/socketio/engine.io/commit/7096e98a02295a62c8ea2aa56461d4875887092d

Syntax:

Syntax:

```js
server.on("connection_error", (err) => {
  console.log(err.req);		// the request object
  console.log(err.code);	// the error code, for example 1
  console.log(err.message);	// the error message, for example "Session ID unknown"
  console.log(err.context);     // some additional error context
});
```

**Closed by darrachequesne** 2021-05-04 08:56 UTC
