### ISSUE TITLE
CORS pre-flight breaks socket.io behind load balancer

### ISSUE THREAD

**Issue by dmkc** [socketio/engine.io#279] opened 2014-09-02 21:17 UTC
I ran into an issue on our servers. We are running socket.io v1.0.6 on multiple server instances behind a load balancer. For polling, the requests go through the ELB with sticky sessions turned on. Our real-time service is on a subdomain, and thanks to CORS pre-flight requests, socket.io fucks up. Here is what happens on the client when the polling transport is used:
1. A socket.io handshake POST request occurs. The response comes back valid with an `sid`, and the headers include the AWS ELB cookie.
2. Next, a pre-flight `OPTIONS` request is made by the browser. The ELB cookie is _not_ included by the browser here. As a result, the `OPTIONS` request is routed to a potentially different server which will not recognize the `sid` in the query string. 
3. When the request is routed to the wrong server, socket.io responds with a 400 HTTP status code and an `Session ID unknown` error.
4. Since the pre-flight request fails, the browser also fails the actual GET polling request, and tries to re-do the handshake from the beginning
5. Possibly due to the headers being sent, the browser sends the `OPTIONS` pre-flight request fairly regularly as opposed to doing it only once, so this cycle repeats over and over.

The fix on our end currently is to respond to all `OPTIONS` requests with a 200 and all the usual `Access-Control-Allow-…` headers the browser knows and loves. We do this before they even get to socket.io in our nginx config.

Now, engine.io appears to already handle this case here: https://github.com/Automattic/engine.io/blob/master/lib/transports/polling-xhr.js#L40 

However, that check is only reached if the `sid` is valid here: https://github.com/Automattic/engine.io/blob/master/lib/server.js#L180 

which it isn't, of course. I can submit a PR but I'd like to know how you guys think it'd be best to handle this. AFAIK, if a request method is `OPTIONS`, we can make the assumption that we are polling. But, since we don't have a valid `sid` to look up a client by, this might mean moving fairly transport-specific logic into `server.js` which sounds less than ideal.

Thoughts?

**Comment by defunctzombie** [comment] 2015-01-10 19:05
Mildly related: https://github.com/Automattic/engine.io/issues/300

**Comment by ashaffer** [comment] 2015-02-20 05:31
+1 for this issue

**Comment by ashaffer** [comment] 2015-02-20 06:21
For anyone else with this issue, the follow code will fix it:

```javascript
var qs = require('querystring');

function prepare(req) {
  if (! req._query) {
    req._query = req.url.indexOf('?') !== -1 ? qs.parse(parse(req.url).query) : {};
  }
}

module.exports = function(srv) {
  var listeners = srv.listeners('request').slice(0);
  srv.removeAllListeners('request');
  srv.on('request', function(req) {
    prepare(req);
    if(req.method === 'OPTIONS' && req.url.indexOf('/socket.io') === 0) {
      if(req._query)
        req._query.sid = null;
    }
  });

  listeners.forEach(function(fn) {
    srv.on('request', fn);
  });
};
```

**Comment by sacheendra** [comment] 2015-03-25 19:53
There is a small addition to the above code that is needed to fix it. 
There needs to be a access-control-allow-headers header

```javascript
module.exports = function(srv) {
  var listeners = srv.listeners('request').slice(0);
  srv.removeAllListeners('request');
  srv.on('request', function(req, res) {
    if(req.method === 'OPTIONS' && req.url.indexOf('/socket.io') === 0) {
      var headers = {};
      if (req.headers.origin) {
        headers['Access-Control-Allow-Credentials'] = 'true';
        headers['Access-Control-Allow-Origin'] = req.headers.origin;
      } else {
        headers['Access-Control-Allow-Origin'] = '*';
      }

      headers['Access-Control-Allow-Methods'] = 'GET,HEAD,PUT,PATCH,POST,DELETE';
      headers['Access-Control-Allow-Headers'] = 'origin, content-type, accept';
      res.writeHead(200, headers);
      res.end();
    } else {
      listeners.forEach(function(fn) {
        fn.call(srv, req, res);
      });
    }
  });
};
```

This solved the problem for me.

**Comment by darrachequesne** [comment] 2016-12-22 07:36
Has this been fixed yet?

> 1. OPTIONS turned off by default on engine.io server side
> 2. By default forceBase64 for XHR if client detects CORS scenario (WS is of course fine)
> 3. Add a forceBinaryXHRCors flag (default=false) which will disable (2) above, thus the browser will emit OPTIONS requests, and the developer will need to turn on the OPTIONS flag server-side.

**Comment by MiLk** [comment] 2017-02-27 02:59
Hello,

I'm trying to set up socket.io servers behind AWS ALB.
The stickiness is using cookies as stated in http://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html#sticky-sessions
> Application Load Balancers support load balancer-generated cookies only. The name of the cookie is AWSALB. The contents of these cookies are encrypted using a rotating key. You cannot decrypt or modify load balancer-generated cookies.

Because the web application and the ALB are not on the same domain, OPTIONS requests are sent during the handshake phase for long-polling.
However the OPTIONS requests don't have cookies attached to them, and are sent following the ALB distribution method instead of being sticky.
The OPTIONS requests being handled late inside the `polling-xhr` transport, there is a [verification step](https://github.com/socketio/engine.io/blob/bd1e81ec3d11f18c5fc09c55745d5ff66d037cc1/lib/server.js#L225-L237) being done early which fails because the [session is not valid on all the servers](https://github.com/socketio/engine.io/blob/bd1e81ec3d11f18c5fc09c55745d5ff66d037cc1/lib/server.js#L160-L162).
All of that leads to the handshake failure.

While I agree that the aforementioned points should be addressed to avoid doing OPTIONS requests, OPTIONS requests should not trigger all the described logic.

The rfc2616 says:
> The OPTIONS method represents a request for information about the communication options available on the request/response chain identified by the Request-URI. This method allows the client to determine the options and/or requirements associated with a resource, or the capabilities of a server, without implying a resource action or initiating a resource retrieval.
From my understanding, OPTIONS should only specify the headers for CORS allowing subsequent requests to be sent.
It SHOULD NOT:
* Verify that the session is valid (https://github.com/socketio/engine.io/blob/bd1e81ec3d11f18c5fc09c55745d5ff66d037cc1/lib/server.js#L225)
* Initiate the handshake (https://github.com/socketio/engine.io/blob/bd1e81ec3d11f18c5fc09c55745d5ff66d037cc1/lib/server.js#L235)
* Try to initiate a connection (https://github.com/socketio/engine.io/blob/bd1e81ec3d11f18c5fc09c55745d5ff66d037cc1/lib/server.js#L316-L339)

I've come up with a way to by-pass the verification steps and delegate earlier the processing of the OPTIONS requests to the transport with https://github.com/MiLk/engine.io/commit/c8012eb24b20dda7b9a679cde8629361cadf2f12
I'm not convinced that's the best way to handle it.
Maybe the handling the OPTIONS requests directly in the listener is a better idea as proposed by other people in this thread.

I'm willing to spend more time on this issue.
What are your views on that?

I'll explore the other solution which is trying to disable CORS by changing the content-type and see where I go with that.

**Comment by JohnCoding94** [comment] 2017-06-14 09:16
Hi @MiLk,

I am also trying to use socket.io behind an AWS ALB.
Could you please share a sample of code enabling us to make the connection on the server side?

I see a lot of peoples having the same issue on stackoverflow, it would be really helpful!

Thanks!

**Comment by MiLk** [comment] 2017-06-14 09:27
Hi @JohnCoding94,

We ended-up disabling the polling transport and forcing all the clients to use websockets, because the `OPTIONS` requests are not sending the cookies, and ALB is using rotating keys for their cookies.

What I did in #484, would allow the handshake to work, but the session would still not be right.

However, it might work if you are not using CORS, because the only issue I can think of is the OPTIONS request done during the handshake. https://github.com/socketio/socket.io-client/blob/master/docs/API.md#with-websocket-transport-only

We have now a few thousands WS connections established staying stable over 24h periods. We force connections to be closed in the middle of the night).

**Comment by JohnCoding94** [comment] 2017-06-14 09:36
@MiLk Thanks for your quick answer!

I also tried to connect the client directly in websocket

``` js
const options = {
  secure: false,
  transports : [ "websocket" ]
};

const socket = io(url, options);
```

But i get a 502: `socket.io-client.js:2 WebSocket connection to 'ws://***.eu-west-1.elasticbeanstalk.com/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 502 error.`

I was thinking it was somewhat related to the CORS context (yes i am also in this configuration).

Did you meet this issue?

**Comment by darrachequesne** [comment] 2017-06-14 10:29
> What I did in #484, would allow the handshake to work, but the session would still not be right.

@MiLk could you please explain why that wouldn't work? Is there something we can fix?

**Comment by MiLk** [comment] 2017-06-15 00:59
The flow I currently see is:
1. GET `/socket.io/?EIO=3&transport=polling&t=...`
2. GET `/socket.io/?EIO=3&transport=polling&t=...&sid=...`
3. OPTIONS `/socket.io/?EIO=3&transport=polling&t=...&sid=...`
4. POST `/socket.io/?EIO=3&transport=polling&t=...&sid=...`

In 1., the session is created. socket.io assigns a sid and ALB create a new cookie.
In 2., we send a new request with the sid provided by socket.io and the cookie sent by ALB.
In 3., we send an OPTIONS request before doing the POST request used in the ping process.
But it seems that OPTIONS requests are not sending the cookies.
(https://fetch.spec.whatwg.org/#cors-protocol-and-credentials `Note that even so, a CORS-preflight request never includes credentials.`).
Because of that, ALB send a new cookie, which might associate the client to the same server or a new server.
In 4., if the cookie links the user to a new server, the ping request will arrive to a server without the session, and we have to re-establish the connection from 1.

All of that is happening because:
* ALB is using rotating keys (http://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html#sticky-sessions `The contents of these cookies are encrypted using a rotating key.`, meaning a different cookie is sent with every request).
* OPTIONS request are assigning a new cookie for sticky sessions.

The only way to make the polling transport in the current state of ALB would be to avoir the preflight requests.

However, it should work fine with any loadbalancer using a consistent hashing algorithm, or without setting a new cookie on preflight requests.

**Comment by JohnCoding94** [comment] 2017-06-15 09:40
@MiLk You may already be aware of that but just for information, i ended up setting a connection from a subdomain to my racine domain using SSL, and any OPTIONS request is made, i didn't set any specific options on my socket.io server.

So it performs the classic long pooling handshake, then switch to websocket protocol, and everything seems to work fine.

**Comment by darrachequesne** [comment] 2017-06-16 21:30
@MiLk maybe a `Access-Control-Allow-Methods: : GET, POST` is missing then?

**Comment by MiLk** [comment] 2017-06-17 01:48
No, it's because the OPTIONS request get a new ALB session cookie, which makes the POST request to go to a server where the socket.io session doesn't exist.
I would need to setup something to test again, but IIRC the error came from https://github.com/socketio/engine.io/blob/master/lib/server.js#L161

**Comment by darrachequesne** [comment] 2017-06-17 07:21
What I meant is adding `Access-Control-Allow-Methods: GET, POST` would remove the OPTIONS request in 3/, right?

0. OPTIONS `/socket.io/?EIO=3&transport=polling&t=...` (allow GET and POST, not only GET)
1. GET `/socket.io/?EIO=3&transport=polling&t=...`
2. GET `/socket.io/?EIO=3&transport=polling&t=...&sid=...`
4. POST `/socket.io/?EIO=3&transport=polling&t=...&sid=...`

**Comment by MiLk** [comment] 2017-06-17 09:05
I'm trying to reproduce the issue, but so far the connection seems actually stable.
![screen shot 2017-06-17 at 18 02 06](https://user-images.githubusercontent.com/29782/27251707-53e5bd86-5387-11e7-810c-3f619c0555a9.png)
![screen shot 2017-06-17 at 18 01 33](https://user-images.githubusercontent.com/29782/27251708-54004ff2-5387-11e7-82b5-3aa85d41eaff.png)

I'm using https://github.com/socketio/engine.io/tree/a63c7b787c54b3a47da7f355826bf2770139c62b.

```js
var app = require('express')();
var cors = require('cors');

app.options('*', cors({
  origin: true,
  methods: 'POST',
  allowedHeaders: ['Content-Type'],
  credentials: true,
}));

var server = require('http').Server(app);
var io = require('socket.io')(server, {
  handlePreflightRequest: false
});

...
```

**Comment by scream314** [comment] 2017-06-19 15:35
__What solved the same issue for me:__
I noticed I had an old version of `socket.io` dropped in my code and it was used instead of an `npm` package or whatever. After switching to an up-t-date version of `socket.io-client` the issue disappeared, there is no `OPTIONS` request sent funking up the `AWSALB` cookie.
Afterwards I tried to reproduce the issue in Chrome, FF and Safari, too, with no success.

@MiLk How do you receive a `400` for the `GET`s above? Is this happening only in Safari? Could you check what does Firefox's `Console` say? (So far it was the best one I used, at least when it comes to meaningful error messages.)

**Comment by MiLk** [comment] 2017-06-20 01:16
Chrome and FF seem to be both OK. Only Safari 10.1.1 has an issue.
But the behaviour is definitely different from what I observed a few months ago.

However, my socket.io client and server libraries are not up-to-date (1.1.0 and 1.8 respectively).
Since we forced our clients to use websockets, it's no longer an issue for us, but we will definitively update everything within a few months, I will be able to give a new feedback then.

**Comment by franza** [comment] 2018-04-30 15:54
Any updates on this issue? Is it really enough to use `handlePreflightRequest: false` and handle `OPTIONS` requests as @MiLk showed?

**Comment by darrachequesne** [comment] 2020-02-13 06:48
That should be fixed in engine.io v4 (see https://github.com/socketio/engine.io/commit/61b949259ed966ef6fc8bfd61f14d1a2ef06d319). The new syntax:

```js
new Server({
  cors: {
    origin: "https://example.com",
    methods: ["GET"],
    allowedHeaders: ["Authorization"],
    credentials: true
  }
})
```
Previously:

```js
new Server({
  handlePreflightRequest: (req, res) => {
    res.writeHead(200, {
      "Access-Control-Allow-Origin": 'https://example.com',
      "Access-Control-Allow-Methods": 'GET',
      "Access-Control-Allow-Headers": 'Authorization',
      "Access-Control-Allow-Credentials": true
    });
    res.end();
  }
})
```

**Closed by darrachequesne** 2020-02-13 06:48 UTC
Labels: Needs documentation, PR welcome
