### ISSUE TITLE
Access-Control-Allow-Origin set to * when no Origin request header

### ISSUE THREAD

**Issue by jordonias** [socketio/engine.io#569] opened 2019-01-07 18:25 UTC
The `Access-Control-Allow-Origin` response header is set to `*` when there is no Origin request header. Wouldn't it be just as effective to not set this response header at all, or have an option to?
https://github.com/socketio/engine.io/blob/cb0ac6fddcad12c454651bf0e1a312a154e228a4/lib/transports/polling-xhr.js#L61-L66

**Comment by darrachequesne** [comment] 2019-01-08 06:50
Well that's a good question! The code was last updated here: https://github.com/socketio/engine.io/commit/a70dcaa9210a8a7b314ceca755f7547297e2478b

If I'm not mistaken, no origin means the request was not sent by a browser. We could maybe replace it with:

```js
if (req.method === 'OPTIONS' && req.headers.origin) { 
  headers['Access-Control-Allow-Credentials'] = 'true'; 
  headers['Access-Control-Allow-Origin'] = req.headers.origin; 
}
```

What is your take on this?

**Comment by jordonias** [comment] 2019-01-08 16:10
While polling the client sends a POST request on `emit`. I believe I would expect the `Access-Control-Allow-Origin` from the response.

https://github.com/socketio/engine.io-client/blob/f62fca4b052b54992d3b1e0c476c62ffd82f216a/lib/transports/polling-xhr.js#L107

Is there any reason to not just do the following?
```
if (req.headers.origin) { 
  headers['Access-Control-Allow-Credentials'] = 'true'; 
  headers['Access-Control-Allow-Origin'] = req.headers.origin; 
}
```

**Comment by jordonias** [comment] 2019-01-10 20:03
@darrachequesne any input on this?

**Comment by alesmenzelsocialbakers** [comment] 2019-05-10 07:52
Hello, i am encountering the same issue with setting access-control headers.
The issue is that the response headers shouldnt be set from the request´s origin header because it doesnt make sense - it basically is the same as "*".

This answer makes it clear how it should be handled: https://stackoverflow.com/a/10636765

**Comment by vandernorth** [comment] 2020-08-03 15:22
> Is there any reason to not just do the following?

From a security perspective this is a bad idea. (Pentesters have fallen over this a couple of times now in our application). You are allowing senders/hackers to add their own resource (e.g. hackers.ru) to the `Access-Control-Allow-Origin` header, which means they can connect to this websocket server from their site/resource. What @alesmenzelsocialbakers says is true, this is not any safer than `*`. 

Having said that, a sane default could be to use the `host` header value  instead of the origin header. Additional there should be more control over these header(s). e.g. by setting an `headers` options on initialization and calling that before sending any headers or a setting for the `Access-Control-Allow-Origin` header which you could set to `"*"` if you want to open your socket for everyone or to a function which can then return the desired value for every request.

If @jordonias / @darrachequesne agree I'm willing to make a PR for this feature.

**Comment by darrachequesne** [comment] 2020-10-05 10:59
It should be fixed in Engine.IO v4, as we now offload the CORS configuration to the [cors](https://www.npmjs.com/package/cors) module.

New syntax:

```js
const { Server } = require('engine.io');

new Server({
  cors: {
    origin: "https://example.com",
    methods: ["GET"],
    allowedHeaders: ["Authorization"],
    credentials: true
  }
});
```

**Closed by darrachequesne** 2020-10-05 10:59 UTC
