### ISSUE TITLE
OPTIONS causes 400 in Firefox and IE10

### ISSUE THREAD

**Issue by awdrius** [socketio/engine.io#288] opened 2014-10-02 12:05 UTC
Hi,

after upgrading socket.io to 1.1.0 Firefox and IE10 started complaining about CORS. The quick fix for the issue was to change engine.io/lib/server.js on line 125:
from
if ('GET' != req.method)
to
if ('GET' !== req.method && 'OPTIONS' !== req.method)

I know that this is not optimal but it works for me. 

P.S. I'm using pure socket.io, without express, restify, etc. If there is a better or a standard way to deal with this - your help is much appreciated.

**Comment by darrachequesne** [comment] 2016-12-22 07:44
Closed as duplicate of https://github.com/socketio/engine.io/issues/279

**Closed by darrachequesne** 2016-12-22 07:44 UTC
